### ISSUE TITLE
 Request for  Accessing Individual Gaze Data from Pico 4E via Unity Integration SDK

### ISSUE THREAD

**Issue by rstaubh** [Pico-Developer/PICO-Unity-Integration-SDK#2]
Hi Pico Team,

I hope this message finds you well. I am currently working on a project that involves eye-tracking functionalities using the Pico 4E headset. As part of our development process, we are looking to obtain individual gaze data through the Unity SDK provided by Pico.

Could you please provide detailed instructions or documentation on how to access and retrieve **individual** gaze data using the Pico 4E Unity SDK? 

Your assistance in this matter would be greatly appreciated, as it will significantly aid us in the successful implementation of eye-tracking features in our project.

Thank you for your time and support.

Best regards,
Romeo

**Comment by eioe** [comment]
Hi @rstaubh , 
did you get this to work and would be willing to share your approach? 
I'm trying to get meaningful data from `PXR_MotionTracking.GetEyeTrackingData(ref info, ref eyeTrackingData)` but without much success. It does output data, but it seems only to depend on the head position, not on the eye movements. 
Any input appreciated!
