### ISSUE TITLE
The type or namespace name 'SystemUpdateCallback' could not be found

### ISSUE THREAD

**Issue by ArnaudC2Care** [Pico-Developer/PICO-Unity-Integration-SDK#5]
SDK: 3.0.4 
Unity: 2021.3.43f1

Since the 3.0 release I get this error message
"The type or namespace name 'SystemUpdateCallback' could not be found (are you missing a using directive or an assembly reference?)"
It works by downloading the SDK from the website but not from git.

**Comment by YolarGames** [comment]
It looks like these files in the package don't have a meta file that could not be generated in the immutable packages folder:

Packages/com.unity.xr.picoxr/Assets/Resources/Shader/PXR_Texture2DBlit.shader
Packages/com.unity.xr.picoxr/Enterprise/android/BAuthLib-1.0.0.aar
Packages/com.unity.xr.picoxr/Enterprise/android/tob_api-release.jar
Packages/com.unity.xr.picoxr/Enterprise/android/tobservicelib-release.aar
Packages/com.unity.xr.picoxr/Enterprise/Scripts/Enums/OnlineSystemUpdateErrorCode.cs
Packages/com.unity.xr.picoxr/Enterprise/Scripts/Enums/OnLineSystemUpdateStatusCode.cs
Packages/com.unity.xr.picoxr/Enterprise/Scripts/Interfaces/SystemUpdateCallback.cs
Packages/com.unity.xr.picoxr/Enterprise/Scripts/Model/OffLineSystemUpdateConfig.cs

**Comment by yangel-yan** [comment]
fixed
